### ISSUE TITLE
impl From<Packet<Data>> for Packet<Ack>

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/tftp#22]
Right now any code that sends an Ack packet calls its constructor directly and manually copies the block number from the Data packet. Implementing the From trait might make client code look a little nicer and reduce margin for error.

**Comment by snasphysicist** [comment]
Hi @connorkuehl I'd like to have a go at this, if that's okay. I'm relatively new to Rust & came here via your comment on r/rust.

**Comment by connorkuehl** [comment]
I'd appreciate that very much, thanks, @snasphysicist! Please don't hesitate to ping me if I can be of any help.

**Comment by snasphysicist** [comment]
I've been looking at this over the weekend and I can't see a way to implement this for `Packet` because I can't 'downcast' to `Data` (maybe unless we use something like [downcast_rs](https://docs.rs/downcast-rs/1.2.0/downcast_rs/)). It's quite simple to provide an implementation that works only for the `Data` type like

```
impl From<Data> for Ack {
    fn from(packet: Data) -> Self {
        Ack { block: packet.block }
    }
}
```

Would this be an acceptable solution? If not, could you give me a pointer for how I could achieve this for a `Packet`? It's possible this is way simpler than I realise... Thanks!

**Comment by connorkuehl** [comment]
How about something like this:

```rust
impl From<Packet<Data>> for Packet<Ack> {
    fn from(data: Packet<Data>) -> Packet<Ack> {
        unimplemented!() // TODO
    }
}
```

**Comment by connorkuehl** [comment]
Hey @snasphysicist, just wanted to check in. Have you tried something similar to my previous comment? If it didn't help any, let me know! We can tackle this together.

**Comment by snasphysicist** [comment]
Hi @connorkuehl thanks for checking in, I did figure it out in the end. I was stupidly trying to implement it for the wrong `Packet` hence my confusion... I'm preparing a PR to open later today.
